version: '3.1'

services: 
    api:
        image: killmeapi
        build: 
            context: ./api
            dockerfile: ./../.docker/api.Dockerfile
        ports: 
            - "3001:3001"
    client:
        image: killmeclient
        build:
            context: ./client
            dockerfile: ./../.docker/client.Dockerfile
        ports:
            - "5000:5000"
        depends_on: 
            - api