version: '3.1'

services: 
    api:
        build: 
            context: ./api
            dockerfile: ./../.docker/api.Dockerfile
        volumes: 
            - ./api/src:/api/src
        ports: 
            - "3001:3001"
        networks: 
            - shared
    client:
        build:
            context: ./client
            dockerfile: ./../.docker/client.Dockerfile
        volumes: 
            - ./client/src:/client/src
        ports:
            - "3000:3000"
        networks:
            - shared
        depends_on: 
            - api
        links:
            - api
networks:
    shared:
        driver: bridge